http:
  middlewares:
    strip-api-prefix:
      stripPrefixRegex:
        regex:
          - "^/api/[a-zA-Z0-9-]+"
          
    add-correlation-id:
      headers:
        customRequestHeaders:
          X-Correlation-ID: ""

